---
# -Dspring.profiles.active=devの時の設定 postgreSQLを使用する
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  sql:
    init:
      mode: never
      schema-locations: classpath:sql/band_member.sql
      data-locations: classpath:sql/band_member-data.sql