---
spring:
  application:
    name: spring-rest-api-sample
  messages:
    encoding: UTF-8
  jackson:
    time-zone: "Asia/Tokyo"

logging:
  level:
    com.rest.api.sample.domain.mapper: debug
    com.rest.api.sample.domain.repository: debug
    org.apache.ibatis: debug
    web: debug

mybatis:
  # mapper.xmlの配置先ディレクトリ
  mapper-locations: com.rest.api.sample.domain.mapper.*.xml
  configuration:
    # スネークケースからキャメルケースへの変換設定
    map-underscore-to-camel-case: true
    # AS句で設定された列名をマップする設定
    use-column-label: true
    # フェッチサイズ
    default-fetch-size: 1000
    # DBからの応答タイムアウト値　秒
    default-statement-timeout: 20
    # 取得した列が全てNullだった場合空のインスタンスを返却する
    return-instance-for-empty-row: true

---
# -Dspring.profiles.active未設定時の設定 誰でも起動できるようにh2をデフォルトにします
spring:
  profiles:
    default: local