---
spring:
  application:
    name: spring-rest-api-sample
  messages:
    encoding: UTF-8
  jackson:
    time-zone: "Asia/Tokyo"

logging:
  level:
    web: debug

---
# -Dspring.profiles.active未設定時の設定 誰でも起動できるようにh2をデフォルトにします
spring:
  profiles:
    default: local