spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:develop;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  sql:
    init:
      # h2使用なので毎回DDLとDMLを投入する
      mode: always
      schema-locations: classpath:sql/band_member.sql
      data-locations: classpath:sql/band_member-data.sql
  h2:
    console:
      enabled: true